// Generated by CoffeeScript 1.4.0
(function() {
  var News, Status, config, mongoose;

  config = require('./config');

  mongoose = require('mongoose');

  mongoose.connect(config.mongourl);

  require('./models/status');

  require('./models/news');

  Status = mongoose.model('Status');

  News = mongoose.model('News');

  Status.remove({}, function(err) {
    var status, url, _i, _len, _ref, _results;
    _ref = ['jwc.scu.edu.cn', 'www.scu.edu.cn'];
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      url = _ref[_i];
      status = new Status({
        from_where: url,
        latest_cmp: 0
      });
      console.log(status);
      _results.push(status.save());
    }
    return _results;
  });

  News.remove({}, function(err) {
    return console.log("removed");
  });

}).call(this);
