// Generated by CoffeeScript 1.4.0
(function() {
  var buildUrl, uniqFilenames, urllib, _;

  _ = require('underscore');

  _.str = require('underscore.string');

  urllib = require('url');

  exports.uniqFilenames = uniqFilenames = function(filenames) {
    filenames = filenames.map(function(filename) {
      return _.str.strLeftBack(filename, '.');
    });
    return filenames = _.uniq(filenames);
  };

  exports.buildUrl = buildUrl = function(url, path) {
    var parsed_url;
    if (!_.str.startsWith(path, '/')) {
      return _.str.strLeftBack(url, '/') + '/' + path;
    } else {
      parsed_url = urllib.parse(url);
      parsed_url.pathname = path;
      return urllib.format(parsed_url);
    }
  };

}).call(this);
