// Generated by CoffeeScript 1.4.0
(function() {
  var $, Iconv, getdom, iconv, myUtil, newsUrlFormat, root_url, urls,
    _this = this;

  myUtil = require('../util');

  Iconv = (require('iconv')).Iconv;

  $ = require('jquery');

  iconv = new Iconv('gbk', 'utf-8');

  root_url = 'http://www.scu.edu.cn/';

  exports.urls = urls = ["http://www.scu.edu.cn/", "http://www.scu.edu.cn/news/index.htm"];

  exports.newsUrlFormat = newsUrlFormat = "/(?:\\\w+\\\/){1,4}webinfo/\\\d+/\\\d+/(\\\d+).\\\w{3}";

  exports.mapper = function(path) {
    var cmpValue;
    cmpValue = (path.match(new RegExp(newsUrlFormat)))[1];
    return [myUtil.buildUrl(root_url, path), parseInt(cmpValue)];
  };

  getdom = function(html) {
    var dom;
    html = iconv.convert(html).toString();
    html = html.replace(/<%.*?%>/g, '');
    return dom = $(html);
  };

  exports.getTitle = function(html) {
    var dom, title;
    dom = getdom(html);
    title = dom.find('td.borderCCCC table tbody tr td span').html();
    return title;
  };

  exports.getContent = function(html) {
    var body, dom;
    dom = getdom(html);
    body = dom.find('#BodyLabel').html();
    return body;
  };

}).call(this);
