// Generated by CoffeeScript 1.4.0
(function() {
  var Schema, StatusSchema, mongoose;

  mongoose = require('mongoose');

  Schema = mongoose.Schema;

  StatusSchema = new Schema({
    from_where: {
      type: String,
      unique: true
    },
    latest_cmp: Number
  });

  mongoose.model('Status', StatusSchema);

}).call(this);
